### ISSUE TITLE
Action Elements are not displayed in 5.2.180909

### ISSUE THREAD

**Issue by mschmidt-she** [e-Spirit/scheduleexecutor#1]
Hello,

thank you very much for providing the module. Unfortunately we are unable to get it running with version 5.2.180909. We installed the module, installed the web component to the ContentCreator-Webapp and restarted the ContentCreator Context. There are still no ActionItems displayed.

Following exception appears in our logs, but we are not sure if it is related to your module:

java.lang.NullPointerException
        at net.she.firstspirit.module.formwizard.ActionItems.loadProperties(ActionItems.java:85)
        at net.she.firstspirit.module.formwizard.ActionItems.setUp(ActionItems.java:41)
        at de.espirit.firstspirit.webedit.server.action.AbstractPublicPluginContextProvider.getPlugins(AbstractPublicPluginContextProvider.java:70)
        at de.espirit.firstspirit.webedit.server.action.ActionManager$ActionMap.initialize(ActionManager.java:424)
        at de.espirit.firstspirit.webedit.server.action.ActionManager._getActions(ActionManager.java:194)
        at de.espirit.firstspirit.webedit.server.action.ActionManager.getActions(ActionManager.java:95)
        at de.espirit.firstspirit.webedit.server.WebeditSpecialistsBroker$WebeditActionsAgentImpl.getActions(WebeditSpecialistsBroker.java:507)
        at de.espirit.firstspirit.webedit.server.action.toolbar.ToolbarActionsPlugin$ProjectActions.getAction(ToolbarActionsPlugin.java:564)
        at de.espirit.firstspirit.webedit.server.action.toolbar.ToolbarActionsPlugin$ProjectActions.getAction(ToolbarActionsPlugin.java:541)
        at de.espirit.firstspirit.webedit.server.action.ActionManager.createServerAction(ActionManager.java:246)
        at de.espirit.firstspirit.webedit.server.action.ActionManager._getActions(ActionManager.java:207)
        at de.espirit.firstspirit.webedit.server.action.ActionManager.getActions(ActionManager.java:79)
        at de.espirit.firstspirit.webedit.server.action.ActionServiceImpl.getActions(ActionServiceImpl.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at de.espirit.firstspirit.webedit.server.control.PollSupportingWebeditService$RPCInvoke.call(PollSupportingWebeditService.java:340)
        at de.espirit.firstspirit.webedit.server.control.PollSupportingWebeditService$ServiceCallPollFeedWrapper.call(PollSupportingWebeditService.java:462)
        at de.espirit.firstspirit.webedit.server.concurrent.ExecutionManager$NamedCallable.call(ExecutionManager.java:318)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at de.espirit.common.util.SuspendableThread.run(SuspendableThread.java:56)

Best Regards
Martin Schmidt

**Comment by mschmidt-she** [comment]
we just realized, that the component is not displayed as an own button, like it was in the presentation from the DevDay. It is located in the tab "Actions" instead.

We are very sorry for the confusion. It works perfectly fine.

Best Regards
Martin Schmidt
